title: Title
url: https://www.open.gov.sg
favicon: /images/1_4_4_SG_Customs_Logo_Version_D_Full_Colour_RGB_FA.png
colors:
  primary-color: "#071d49"
  secondary-color: "#009cde"
  media-colors:
    - title: media-color-one
      color: "#a2aaad"
    - title: media-color-two
      color: "#00b0b9"
    - title: media-color-three
      color: "#009cde"
    - title: media-color-four
      color: "#4d4d4f"
    - title: media-color-five
      color: "#071d49"
resources_name: resource
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://customs-test-staging.netlify.app
prod: https://customs-test-prod.netlify.app
facebook-pixel: ""
shareicon: /images/1_4_1_SG_Customs_Logo_Version_A_Full_Colour_RGB_FA.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
